"""Whoop sport_id to human-readable name mapping."""

SPORT_NAMES: dict[int, str] = {
    -1: "Activity",
    0: "Running",
    1: "Cycling",
    16: "Baseball",
    17: "Basketball",
    18: "Rowing",
    19: "Fencing",
    20: "Field Hockey",
    21: "Football",
    22: "Golf",
    24: "Ice Hockey",
    25: "Lacrosse",
    27: "Rugby",
    28: "Sailing",
    29: "Skiing",
    30: "Soccer",
    31: "Softball",
    32: "Squash",
    33: "Swimming",
    34: "Tennis",
    35: "Track & Field",
    36: "Volleyball",
    37: "Water Polo",
    38: "Wrestling",
    39: "Boxing",
    40: "Skateboarding",
    41: "Backcountry Skiing",
    42: "Dance",
    43: "Pilates",
    44: "Yoga",
    45: "Weightlifting",
    46: "CrossFit",
    47: "Stretching",
    48: "Functional Fitness",
    49: "Martial Arts",
    50: "Walking",
    51: "Handball",
    52: "Hiking",
    53: "Rock Climbing",
    54: "Parkour",
    55: "Meditation",
    63: "Cat Stretch",
    71: "Miscellaneous",
    96: "HIIT",
}


def get_sport_name(sport_id: int) -> str:
    return SPORT_NAMES.get(sport_id, f"Activity ({sport_id})")
